name: htci
description: "A new Flutter project."

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.3.4 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  curved_navigation_bar: ^1.0.6  # Use the latest version available
  animator: ^3.1.1
  cupertino_icons: ^1.0.6

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0


flutter:


  uses-material-design: true


  assets:
    - image/templle.jpg
    - image/Htci.png
    - image/night.jpeg
    - image/hq.jpg
    - image/da.png
    - image/don.png
    - image/rat.png
    - image/poo.png
    - image/gg.jpeg
    - image/logo.gif
    - image/dal.jpeg
    - image/dosa.jpeg
    - image/rajma.jpeg
    - image/rice.jpeg
    - image/roti.jpeg
    - image/li.png
    - image/ga.png
    - image/ee.png
